# === tambahan dotfiles-aro.minimal (ditempel di akhir config.example) ===
exec = pipewire
exec = wireplumber
exec = pipewire-pulse
exec = mako
exec = udiskie --no-tray --notify
bind = ctrl+alt+Delete, spawn, powermenu
bind = mod+e, spawn, kitty -e spf
bind = mod+n, spawn, kitty -e nmtui
bind = mod+shift+c, spawn, cheatsheet
